<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="5" skipped="0" tests="7" time="0.133" timestamp="2022-01-19T09:38:10.127095" hostname="DESKTOP-BLEP6BL"><testcase classname="test_bb.TestByteBuffer2" name="test_ctor" file="test_bb.py" line="16" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_bb.TestByteBuffer2" name="test_get_ascii2" file="test_bb.py" line="40" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_bb.TestByteBuffer2" name="test_get_unicode" file="test_bb.py" line="47" time="0.001"><failure message="AssertionError: '\x11&quot;3D' != '한글'&#10;- #x11&quot;3D&#10;+ 한글">self = &lt;test_bb.TestByteBuffer2 testMethod=test_get_unicode&gt;

    def test_get_unicode(self):
        bb = ByteBuffer2(b'\xed\x95\x9c\xea\xb8\x80')
        r = self.bb.get_unicode()
&gt;       self.assertEqual(r, "한글")
E       AssertionError: '\x11"3D' != '한글'
E       - #x11"3D
E       + 한글

test_bb.py:51: AssertionError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_bb.TestByteBuffer2" name="test_uint2_be" file="test_bb.py" line="24" time="0.001"><failure message="NameError: name 'advance' is not defined">self = &lt;test_bb.TestByteBuffer2 testMethod=test_uint2_be&gt;

    def test_uint2_be(self):
&gt;       self.assertEqual(self.bb.get_uint2_be(), 0x1122)

test_bb.py:26: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;Bytebuffer2.ByteBuffer2 object at 0x000001440C72DC10&gt;, at = -1

    def get_uint2_be(self, at = -1):
&gt;       here = advance(at, 2)
E       NameError: name 'advance' is not defined

Bytebuffer2.py:42: NameError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_bb.TestByteBuffer2" name="test_uint2_le" file="test_bb.py" line="20" time="0.001"><failure message="NameError: name 'advance' is not defined">self = &lt;test_bb.TestByteBuffer2 testMethod=test_uint2_le&gt;

    def test_uint2_le(self):
&gt;       self.assertEqual(self.bb.get_uint2_le(), 0x2211)

test_bb.py:22: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;Bytebuffer2.ByteBuffer2 object at 0x000001440C7AF460&gt;, at = -1

    def get_uint2_le(self, at = -1):
&gt;       here = advance(at, 2)
E       NameError: name 'advance' is not defined

Bytebuffer2.py:37: NameError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_bb.TestByteBuffer2" name="test_uint4_be" file="test_bb.py" line="32" time="0.001"><failure message="NameError: name 'advance' is not defined">self = &lt;test_bb.TestByteBuffer2 testMethod=test_uint4_be&gt;

    def test_uint4_be(self):
&gt;       self.assertEqual(self.bb.get_uint4_be(), 0x11223344)

test_bb.py:34: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;Bytebuffer2.ByteBuffer2 object at 0x000001440C7628B0&gt;, at = -1

    def get_uint4_be(self, at = -1):
&gt;       here = advance(at, 4)
E       NameError: name 'advance' is not defined

Bytebuffer2.py:52: NameError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_bb.TestByteBuffer2" name="test_uint4_le" file="test_bb.py" line="28" time="0.001"><failure message="NameError: name 'advance' is not defined">self = &lt;test_bb.TestByteBuffer2 testMethod=test_uint4_le&gt;

    def test_uint4_le(self):
&gt;       self.assertEqual(self.bb.get_uint4_le(), 0x44332211)

test_bb.py:30: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;Bytebuffer2.ByteBuffer2 object at 0x000001440C795280&gt;, at = -1

    def get_uint4_le(self, at = -1):
&gt;       here = advance(at, 4)
E       NameError: name 'advance' is not defined

Bytebuffer2.py:47: NameError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>