<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="4" skipped="0" tests="6" time="0.126" timestamp="2022-01-19T09:37:46.145487" hostname="DESKTOP-BLEP6BL"><testcase classname="test_bb.TestByteBuffer2" name="test_ctor" file="test_bb.py" line="16" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_bb.TestByteBuffer2" name="test_get_ascii2" file="test_bb.py" line="40" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_bb.TestByteBuffer2" name="test_uint2_be" file="test_bb.py" line="24" time="0.001"><failure message="NameError: name 'advance' is not defined">self = &lt;test_bb.TestByteBuffer2 testMethod=test_uint2_be&gt;

    def test_uint2_be(self):
&gt;       self.assertEqual(self.bb.get_uint2_be(), 0x1122)

test_bb.py:26: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;Bytebuffer2.ByteBuffer2 object at 0x000001CD476C3130&gt;, at = -1

    def get_uint2_be(self, at = -1):
&gt;       here = advance(at, 2)
E       NameError: name 'advance' is not defined

Bytebuffer2.py:37: NameError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_bb.TestByteBuffer2" name="test_uint2_le" file="test_bb.py" line="20" time="0.001"><failure message="NameError: name 'advance' is not defined">self = &lt;test_bb.TestByteBuffer2 testMethod=test_uint2_le&gt;

    def test_uint2_le(self):
&gt;       self.assertEqual(self.bb.get_uint2_le(), 0x2211)

test_bb.py:22: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;Bytebuffer2.ByteBuffer2 object at 0x000001CD4771D550&gt;, at = -1

    def get_uint2_le(self, at = -1):
&gt;       here = advance(at, 2)
E       NameError: name 'advance' is not defined

Bytebuffer2.py:32: NameError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_bb.TestByteBuffer2" name="test_uint4_be" file="test_bb.py" line="32" time="0.001"><failure message="NameError: name 'advance' is not defined">self = &lt;test_bb.TestByteBuffer2 testMethod=test_uint4_be&gt;

    def test_uint4_be(self):
&gt;       self.assertEqual(self.bb.get_uint4_be(), 0x11223344)

test_bb.py:34: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;Bytebuffer2.ByteBuffer2 object at 0x000001CD476EA4C0&gt;, at = -1

    def get_uint4_be(self, at = -1):
&gt;       here = advance(at, 4)
E       NameError: name 'advance' is not defined

Bytebuffer2.py:47: NameError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_bb.TestByteBuffer2" name="test_uint4_le" file="test_bb.py" line="28" time="0.001"><failure message="NameError: name 'advance' is not defined">self = &lt;test_bb.TestByteBuffer2 testMethod=test_uint4_le&gt;

    def test_uint4_le(self):
&gt;       self.assertEqual(self.bb.get_uint4_le(), 0x44332211)

test_bb.py:30: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;Bytebuffer2.ByteBuffer2 object at 0x000001CD47701AC0&gt;, at = -1

    def get_uint4_le(self, at = -1):
&gt;       here = advance(at, 4)
E       NameError: name 'advance' is not defined

Bytebuffer2.py:42: NameError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>